version: 2.1

executors:
  my-jdk14:
    docker:
      - image: circleci/openjdk:14.0.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          executor: my-jdk14