#      - maven/test # checkout, build, test, and upload test results
version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jabs:
  test:
    executor:
      name: maven/default
      tag: '14.0.1'
    steps:
      - checkout
#      - maven/with_cache
#      - maven/process_test_results

workflows:
  maven_test:
    jobs:
      - test
